### PR TITLE
Type fixes

### PR DESCRIPTION
**Pull request by udondan**
This addresses #6.

Not sure how the file `lib/index.d.ts` is supposed to be generated. It doesn't update when you run `npm run build`. Manually fixed it.

The last line in `src/types.ts` didn't compile for me, removing it and building the lib seems to fix it.

Not sure if you want to merge this in as is. Just showing what I have done to get this lib working.

### CODE REVIEW

**Comment by hanwencheng** [comment]
Thanks for fix the types bug, I am not sure what causes the importing error, but according to my node.js and React app setup, the current exporting works well. Just want to make sure this change support all kinds of exports.

So would like to merge it just with the types fix, about the export module changes, I will need some more time to check it.

**Comment by udondan** [comment]
> So would like to merge it just with the types fix

I reverted the export changes, just the type fixes in the PR now.

> about the export module changes, I will need some more time to check it.

In the meantime I published a scoped package, including the export changes: https://www.npmjs.com/package/@udondan/common-substrings. Without these changes I just cannot call the `substrings` method.

Great package! I'm using it now in https://github.com/udondan/iam-floyd

**Review by hanwencheng — APPROVED** [review]

**Comment by hanwencheng** [comment]
Thank you! nice to know that the library helps!

**Comment by tbartley** [comment]
Hi @hanwencheng - it seems that this fix has not been published to npmjs yet. Is that something you are able to do?

**Pull request merged**
